security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory:
            memory: ~
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        oauth_token:
            pattern:    ^(/oauth/v2/token|/api/user/login)
            security:   false
        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true
            anonymous:  true
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        default:
            anonymous: ~
    role_hierarchy:
        ROLE_ADMIN: ROLE_API
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    access_control:
        - { path: ^/api/register, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }
        - { path: ^/api/categories, roles: [ ROLE_ADMIN ], methods: [POST, PUT, DELETE] }
        - { path: ^/api/status, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ], methods: [GET] }
        - { path: ^/api/categories, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ], methods: [GET] }
        - { path: ^/api/notifications, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ], methods: [GET] }
        - { path: ^/api, roles: [ ROLE_API ]}

