MailAppBundle\Entity\Subscriber:
  properties:
      email:
          - Email:
              message: The email "{{ value }}" is not a valid email.
              checkMX: false
#      user:
#          - NotBlank: ~
      attributes:
          - Valid: ~
          - All:
              - NotNull: ~