MailAppBundle\Entity\Subscriber:
  exclusion_policy: ALL
  properties:
    id:
      expose: true
      groups: [SUBSCRIBER_DETAILS]
    email:
      expose: true
      groups: [SUBSCRIBER_DETAILS]
    createdAt:
      expose: true
      groups: [SUBSCRIBER_DETAILS]
      type: DateTime<'Y-m-d'>
    attributes:
      expose: true
      groups: [SUBSCRIBER_DETAILS]
      type: ArrayCollection<MailAppBundle\Entity\Attribute>
      max_depth: 2