MailAppBundle\Entity\Attribute:
  exclusion_policy: ALL
  properties:
    id:
      expose: false
      groups: [ATTRIBUTE_DETAILS]
    name:
      expose: true
      groups: [ATTRIBUTE_DETAILS]
    value:
      expose: true
      groups: [ATTRIBUTE_DETAILS]