register:
  path:     /register
  defaults: { _controller: ApiBundle:User:register, _format: json }
  methods: [POST]

status:
  path:     /status
  defaults: { _controller: ApiBundle:Status:index, _format: json }
  methods: [GET]

user_show:
  path:     /profile
  defaults: { _controller: ApiBundle:User:profile, _format: json }
  methods: [GET]

subscriber_group_show:
  path:     /groups
  defaults: { _controller: ApiBundle:SubscriberGroup:index, _format: json }
  methods: [GET]

subscriber_group_create:
  path:     /groups
  defaults: { _controller: ApiBundle:SubscriberGroup:create, _format: json }
  methods: [POST]

subscriber_group_delete:
  path: /groups/{id}
  defaults:  { _controller: ApiBundle:SubscriberGroup:delete, _format: json }
  methods:  [DELETE]

subscriber_show:
  path:     /subscribers
  defaults: { _controller: ApiBundle:Subscriber:index, _format: json }
  methods: [GET]

subscriber_create:
  path:     /subscribers
  defaults: { _controller: ApiBundle:Subscriber:create, _format: json }
  methods: [POST]

subscriber_delete:
  path: /subscribers/{id}
  defaults:  { _controller: ApiBundle:Subscriber:delete, _format: json }
  methods:  [DELETE]