########## USER ##########
user_show:
  path:     /profile
  defaults: { _controller: ApiBundle:User:profile, _format: json }
  methods: [GET]

register:
  path:     /register
  defaults: { _controller: ApiBundle:User:register, _format: json }
  methods: [POST]
