MailAppBundle\Entity\AuthCode:
  type: entity
  table: authcode
  id:
    id:
      type: integer
      generator:
        strategy: AUTO

  manyToOne:
    client:
      targetEntity: Client
      joinColumn:
        nullable: false
    user:
        targetEntity: User

  lifecycleCallbacks: {  }
