MailAppBundle\Entity\RefreshToken:
  type: entity
  table: refreshtoken
  id:
    id:
      type: integer
      generator:
        strategy: AUTO

  manyToOne:
    client:
      targetEntity: Client
      joinColumn:
        nullable: false
    user:
      targetEntity: User

  lifecycleCallbacks: {  }
