MailAppBundle\Entity\Subscriber:
  type: entity
  table: subscriber
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
      email:
          column: email
          type: string
          nullable: false
          length: 255
      createdAt:
          column: created_at
          type: datetime
          nullable: false
  manyToOne:
      user:
           targetEntity: User
           inversedBy: subscriber
           joinColumn:
              name: user_id
              referencedColumnName: id
              nullable: true
  oneToMany:
       attributes:
           targetEntity: Attribute
           mappedBy: subscriber
           cascade: ["all"]

  lifecycleCallbacks: {  }
