MailAppBundle\Entity\Subscriber:
  type: entity
  table: subscriber
  repositoryClass: MailAppBundle\Repository\SubscriberRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
      email:
          column: email
          type: string
          nullable: false
          length: 255
      active:
          column: active
          type: boolean
          options:
              default: 1
      createdAt:
          column: created_at
          type: datetime
          nullable: false
  manyToOne:
      subscriberGroup:
           targetEntity: SubscriberGroup
           inversedBy: subscriber
           joinColumn:
              name: subscriber_group_id
              referencedColumnName: id
              nullable: true
  oneToMany:
       attributes:
           targetEntity: Attribute
           mappedBy: subscriber
           cascade: ["all"]

  lifecycleCallbacks: {  }
