MailAppBundle\Entity\User:
  type: entity
  table: fos_user
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  oneToMany:
       subscriberGroups:
           targetEntity: SubscriberGroup
           mappedBy: user
           cascade: ["all"]

  lifecycleCallbacks: {  }
