---
- name: Install python-pycurl
  apt: pkg=python-pycurl state=latest

- name: Add PHP repo
  apt_repository: repo="ppa:ondrej/php"

- name: Install PHP
  apt: name=php7.1 state=latest force=yes

- name: Intsall PHP packages
  apt: name={{ item }} state=latest force=yes
  with_items:
    - php7.1-cli
    - php7.1-gd
    - php7.1-mysql
    - php7.1-curl
    - php7.1-mcrypt
    - php7.1-dev
    - php-pear
    - php7.1-fpm
    - php7.1-mbstring
    - php7.1-zip
    - php7.1-intl
    - php-memcache
    - memcached

- name: Configure PHP
  template: src=php_config.ini.j2 dest=/etc/php/7.1/fpm/conf.d/php_config.ini force=yes



